version: "3.9"
services:
  app:
    build: .
    image : "demo-service"
    ports:
      - "8000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/demo
      PORT : 3000
      WAIT_HOSTS: mongodb:27017
  mongodb:
    image: "mongo:latest"
    hostname: mongodb
    ports: 
      - "27017:27017"
    volumes:
      - './data:/data/db'