---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort         # Virtual IP + map host port
  selector:
    app: app-lable       # Label selector
  ports:
    - protocol: TCP      # Protocol
      port: 8080           # Port của service
      targetPort: 3000   # Port của pod
      nodePort: 30007    # Port của host (optional)
