apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    something: mongodb-label
spec:
  replicas: 1                  # Number of pods
  selector:                    #
    matchLabels:               # This selector MUST MATCH below labels
      app: mongodb-label          #

  # Pod template
  template:
    metadata:
      name: mongodb-pod                
      labels:
        app: mongodb-label        # Pod labels
    spec:
      containers:                       
        - name: db                     
          image: mongo      
          imagePullPolicy: Always       
          ports:
            - containerPort: 27017